export const localStorageDashboardWelcomeTourKey = 'flossbank_u_show_welcome_tour'
export const localStorageLoggedIn = 'flossbank_u_logged_in'
export const localStorageGHStateKey = 'flossbank_u_gh_state'
export const localStoragePackageKey = 'flossbank_package'
export const localStorageMaintainerKey = 'flossbank_maintainer'
